export const FETCH_PORTS_REQUEST = 'FETCH_PORTS_REQUEST'
export const FETCH_PORTS_SUCCESS = 'FETCH_PORTS_SUCCESS'
export const FETCH_PORTS_FAILURE = 'FETCH_PORTS_FAILURE'

export const ADD_PORT = 'ADD_PORT'
export const REMOVE_PORT = 'REMOVE_PORT'
export const BIND_PORT = 'BIND_PORT'
export const UNBIND_PORT = 'UNBIND_PORT'
