export const FETCH_NODES_REQUEST = 'FETCH_NODES_REQUEST'
export const FETCH_NODES_SUCCESS = 'FETCH_NODES_SUCCESS'
export const FETCH_NODES_FAILURE = 'FETCH_NODES_FAILURE'

export const INIT_NODE = 'INIT_NODE'
export const UPDATE_NODE = 'UPDATE_NODE'
export const DISCONNECT_NODE = 'DISCONNECT_NODE'
